# Generated by Django 3.2.7 on 2021-09-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20210918_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='header_images',
        ),
    ]
