# Generated by Django 3.2.7 on 2021-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_auto_20210919_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biograph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
